[package]
name = "frc-sys"
version = "0.1.0"
authors = ["Andrew (Andy) Min <me@andrewmin.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.58.1"
chrono = "0.4.19"